import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { normalizeManagedSignalBlock } from "../../src/repo/signal-block.mjs";

/**
 * The brand ratchet: the live tree carries one name, and it is Faberun.
 *
 * This file owns the rule the rename leaves behind. It reads every tracked text
 * file in the repository and fails if the previous brand survives anywhere, so
 * the old name cannot return one comment or environment variable at a time. The
 * second test pins the two package.json facts the rename is really about: the
 * package name and the executable a `npx`/install run resolves to.
 *
 * The file list comes from `git ls-files`, not a directory walk: the scan must
 * cover tracked source only, so it cannot fail on a scratch file a developer
 * left lying around, nor drift from `.gitignore` the way a hand-maintained
 * directory deny-list would. `.git/`, `.runs/` and `node_modules/` never appear
 * in `git ls-files` output for that reason, and `assets/` holds binary art that
 * no extension in `TEXT_EXTENSIONS` matches -- neither needs naming here.
 *
 * The excluded paths below are records, not stale paths. `docs/history/` and
 * `docs/campaigns/` hold accepted specs, retrospectives and the contracts a
 * worker was actually given; `evals/golden/` holds frozen fixtures. Each was
 * written at a moment in time and says so; editing one to match the present
 * would make the record lie about the run it documents.
 */

const REPO_DIR = fileURLToPath(new URL("../..", import.meta.url));

/** The previous brand, in every spelling it appeared in: hyphen, underscore, space or none. */
export const LEGACY_NAME_PATTERN = /intent[-_ ]?factory/iu;

/** Repository-relative paths whose contents are historical record. */
// CHANGELOG.md is generated by release-please from commit subjects, so it
// carries every historical scope verbatim; a record, like docs/history.
const SKIPPED_PATHS = new Set(["docs/history", "docs/campaigns", "evals/golden", "evals/planner", "CHANGELOG.md"]);

/** Only text files carry the brand; every extension the tree's prose and code use. */
const TEXT_EXTENSIONS = new Set([
  ".mjs", ".js", ".json", ".md", ".yml", ".yaml", ".sh", ".html", ".css", ".txt", ".toml",
]);

/**
 * @param {string} label repository-relative, forward-slash path
 * @returns {boolean} whether `label` is or is under a `SKIPPED_PATHS` entry
 */
function isSkippedPath(label) {
  for (const skip of SKIPPED_PATHS) {
    if (label === skip || label.startsWith(`${skip}/`)) return true;
  }
  return false;
}

/**
 * @returns {string[]} repository-relative paths of every tracked text file
 */
function trackedTextFiles() {
  const output = execFileSync("git", ["-C", REPO_DIR, "ls-files", "-z"], { encoding: "utf8" });
  return output.split("\0").filter((label) => {
    if (label === "" || isSkippedPath(label)) return false;
    const dot = label.lastIndexOf(".");
    return dot >= 0 && TEXT_EXTENSIONS.has(label.slice(dot));
  });
}

const FILES = trackedTextFiles().map((label) => ({
  label,
  // The managed signal block mirrors run directory names under .runs/, which
  // are records of campaigns that already happened (some still carry the old
  // name); the block is machine-written and excluded like .runs itself.
  text: normalizeManagedSignalBlock(readFileSync(join(REPO_DIR, label), "utf8")),
}));

test("no live file carries the previous brand name", () => {
  /** @type {string[]} */
  const offenders = [];
  for (const file of FILES) {
    for (const [index, line] of file.text.split("\n").entries()) {
      if (LEGACY_NAME_PATTERN.test(line)) offenders.push(`${file.label}:${index + 1}`);
    }
  }
  assert.deepEqual(
    offenders,
    [],
    `the previous brand survives on ${offenders.length} line(s):\n${offenders.map((line) => `  ${line}`).join("\n")}`,
  );
});

test("package.json names the package faberun and its entry point bin/faberun.mjs", () => {
  const pkg = /** @type {{name?: string, bin?: Record<string, string>}} */ (
    JSON.parse(readFileSync(join(REPO_DIR, "package.json"), "utf8"))
  );
  assert.equal(pkg.name, "faberun");
  assert.equal(pkg.bin?.faberun, "bin/faberun.mjs");
});
